<div class="wrapper">
	<header class="nav-header">
		<ul class="page-nav">
			<li><a class="header-link" href="home">Chaplin Example</a></li>
			<li><a class="header-link" href="wall">Wall</a></li>
			<li><a class="header-link" href="timeline">Timeline</a></li>

		</ul>
		<div id="navigation"></div>
	</header>
	<section class="page-container">
		<div id="login-container"></div>
		<div id="friends-container" class="nav-sidebar">
		</div>
		<div class="home-page">
			<div id="message-form-container"></div>
			<div id="conversation-container"></div>
		</div>
	</section>
</div>