<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Backbone Api'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le styles -->
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css') ?>
       <script src="<?php echo $this->basePath() ?>/js/backbone/libs/require.js" data-main="<?php echo $this->basePath() ?>/js/backbone/apps/app"></script>
    </head>
    <body>
        <?php echo $this->content;?>
    </body>
</html>

