<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Backbone And Require Js</title>
<link href="css/style.css" rel="stylesheet">
<script data-main="js/backbone/apps/app" src="js/backbone/libs/require.js"></script>
</head>

<body>
	<div class="wrapper">
	<div class="menu">
		<a href = "#release">Release</a>
		<a href = "#track">Track</a>
		
	</div>
		<div class="content-wrapper">
			<div class="result">
				<div  id="results">
					<table id="releases">
					</table>
					<table id="tracks">
					</table>
				</div>
				<span class="show-more"><a id="show_more" href="javascript:void(0);">Show
						More</a>
						</span>
			</div>
			<div class="datasets">
				<table id="s-release" border="1" cellspacing="0">				
				</table>
			</div>
		</div>
	</div>
	<script type="text/template" id="releases-template">
		<td><a id="<%= releaseId %>" href ="javascript:void(<%= releaseId %>)"><%= releaseName.substring(0,40) %></a></td>
	</script>
	<script type="text/template" id="tracks-template">
		<td><a id="<%= trackId %>" href ="javascript:void(<%= trackId %>)"><%= trackName.substring(0,40) %></a></td>
	</script>
	
		<script type="text/template" id="single-release-template">
			<tr><td class="col1">Release id</td><td class="col2"><%= release_id %></td></tr>
			<tr><td class="col1">Release Name</td><td class="col2"><%= release_name %></td></tr>
			<tr><td class="col1">Release Date</td><td class="col2"><%= release_date %></td></tr>
			<tr><td class="col1">Release UPC</td><td class="col2"><%= upc %></td></tr>
			<tr><td class="col1">Genre Id</td><td class="col2"><%= genre_id %></td></tr>
			<tr>
				<td colspan= "2" align="right">
					<a href ="javascript:void(<%= release_id %>)" class="btnEditRelease" id="<%= release_id %>">Edit </a>
				</td>
			</tr>
		</script>
	
	<script id="release-edit-template" type="text/template">
		<tr><td>Release Id</td><td class="col2"><%= release_id %></td></tr>
        <tr><td>Release Name</td><td><input id="releaseName" class="editInput" value="<%= release_name %>"/></td></tr>	
		<tr><td>Release Date</td><td><input id="releaseDate" class="editInput" value="<%= release_date %>"/></td></tr>	
		<tr><td>UPC</td><td><input id="releaseUpc" class="editInput" value="<%= upc %>"/></td></tr>
		<tr><td>Genre Id</td><td><%= genre_id %></td></tr>      
		<tr>
        <td colspan= "2" align="center">
        	<input class="btnSaveRelease" id="<%= release_id %>" type="button" value="Save"/>
        	<input class="btnCancel" id="<%= release_id %>" type="button" value="Cancel"/>
        </td>
		</tr>
	</script>
</body>
</html>